services:
  spring-observability:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: spring-observability
    ports:
      - "8080:8080"
    networks:
      - observabilityNetwork

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - observabilityNetwork

  grafana:
#    image: grafana/grafana-enterprise
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/provisioning:/etc/grafana/provisioning
#    environment:
#      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH= ./monitoring/provisioning/dashboards/spring-boot-dashboard.json
    networks:
      - observabilityNetwork

networks:
  observabilityNetwork:
    driver: bridge