services:
  spring-observability:
    image: spring-observability:1.0.0
    container_name: spring-observability
    ports:
      - "8080:8080"
    networks:
      - observabilityNetwork

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - observabilityNetwork

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - observabilityNetwork

networks:
  observabilityNetwork:
    driver: bridge