spring:
  application:
    name: SpringObservability
  datasource:
    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
#    root: debug
    com.zaxxer.hikari: DEBUG
